using System.Collections.Generic;
using UnityEngine;
using CityBuilder.WorldState;

namespace CityBuilder.Interiors
{
    /// <summary>
    /// Holds the nested room layout generated by the Interior agent for a
    /// building. Rooms are represented as simple child GameObjects sized
    /// by their bounding box -- enough for the compile/validation loop and
    /// for later visual work to build on.
    /// </summary>
    public class InteriorBehaviour : MonoBehaviour
    {
        public List<Room> Rooms = new List<Room>();

        public void Apply(Interior interior)
        {
            if (interior == null)
            {
                return;
            }

            Rooms = interior.rooms;

            // Clear any previously generated room markers before re-applying,
            // so re-running Apply() stays idempotent.
            foreach (Transform child in transform)
            {
                if (child.name.StartsWith("room:"))
                {
                    Destroy(child.gameObject);
                }
            }

            foreach (Room room in Rooms)
            {
                var roomObject = new GameObject($"room:{room.id}:{room.name}");
                roomObject.transform.SetParent(transform, false);
                roomObject.transform.localPosition = new Vector3(room.position.x, room.position.y, room.position.z);
                roomObject.transform.localScale = new Vector3(room.size.x, room.size.y, room.size.z);
            }
        }
    }
}
