using System;
using System.Collections.Generic;

namespace CityBuilder.WorldState
{
    /// <summary>
    /// Root document persisted at world_state.json. This is the single source of
    /// truth for every object that exists in the world. Nothing is regenerated
    /// from scratch -- agents read this file, mutate it, and the scene is
    /// rebuilt (additively) from its contents.
    /// </summary>
    [Serializable]
    public class WorldStateDocument
    {
        public int version = 1;
        public List<WorldObject> objects = new List<WorldObject>();
    }

    /// <summary>
    /// A single object placed in the world: a building, tree, or decoration.
    /// Buildings may own a nested list of child decorations and an optional
    /// interior layout.
    /// </summary>
    [Serializable]
    public class WorldObject
    {
        /// <summary>Stable identifier, e.g. "building-1", "tree-4".</summary>
        public string id;

        /// <summary>"building" | "tree" | "decoration".</summary>
        public string type;

        public Vector3Data position = new Vector3Data();
        public Vector3Data scale = new Vector3Data(1, 1, 1);

        /// <summary>
        /// Free-form key/value properties (e.g. color, style, height).
        /// Stored as a list, not a Dictionary -- Unity's JsonUtility cannot
        /// serialize/deserialize Dictionary fields and would silently drop
        /// them.
        /// </summary>
        public List<PropertyEntry> properties = new List<PropertyEntry>();

        /// <summary>Child decoration objects attached to this object (e.g. trees around a building).</summary>
        public List<WorldObject> children = new List<WorldObject>();

        /// <summary>Present only on buildings that have had an interior generated.</summary>
        public Interior interior;
    }

    [Serializable]
    public class PropertyEntry
    {
        public string key;
        public string value;

        public PropertyEntry() { }

        public PropertyEntry(string key, string value)
        {
            this.key = key;
            this.value = value;
        }
    }

    [Serializable]
    public class Vector3Data
    {
        public float x;
        public float y;
        public float z;

        public Vector3Data() { }

        public Vector3Data(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }

    /// <summary>Nested room layout generated by the Interior agent for a building.</summary>
    [Serializable]
    public class Interior
    {
        public List<Room> rooms = new List<Room>();
    }

    [Serializable]
    public class Room
    {
        public string id;
        public string name;
        public Vector3Data position = new Vector3Data();
        public Vector3Data size = new Vector3Data(1, 1, 1);
    }
}
